worker_1:
  queues: 'turbot_docker_runs'
worker_2:
  queues: 'turbot_docker_runs'
worker_3:
  queues: 'turbot_docker_runs'
worker_4:
  queues: 'turbot_docker_runs'
worker_5:
  queues: 'turbot_docker_runs'
worker_6:
  queues: 'turbot_docker_runs'
worker_7:
  queues: 'turbot_docker_runs'
worker_8:
  queues: 'turbot_docker_runs'
worker_9:
  queues: 'turbot_docker_runs'
worker_10:
  queues: 'turbot_docker_runs'
worker_11:
  queues: 'turbot_docker_runs'
worker_12:
  queues: 'turbot_docker_runs'
worker_13:
  queues: 'turbot_docker_runs'
worker_14:
  queues: 'turbot_docker_runs'
worker_15:
  queues: 'turbot_docker_runs'
